# Generated by Django 4.2.16 on 2024-09-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalUser',
            fields=[
                ('idhospitaluser', models.AutoField(db_column='idHospitalUser', primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(db_column='fechaAsignacion')),
            ],
            options={
                'db_table': 'HospitalUser',
                'managed': False,
            },
        ),
    ]
