# Generated by Django 4.2.16 on 2024-09-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('idcama', models.AutoField(db_column='idCama', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(db_column='nombreCompleto', max_length=200)),
                ('esta_ocupada', models.BooleanField(db_column='estaOcupada', default=False)),
            ],
            options={
                'db_table': 'Cama',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirectorHospital',
            fields=[
                ('iddirectorhospital', models.AutoField(db_column='idDirectorHospital', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(db_column='fechaInicio')),
                ('fecha_fin', models.DateField(blank=True, db_column='fechaFin', null=True)),
            ],
            options={
                'db_table': 'DirectorHospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('idhabitacion', models.AutoField(db_column='idHabitacion', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(db_column='nombreCompleto', max_length=200)),
            ],
            options={
                'db_table': 'Habitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('idhospital', models.AutoField(db_column='idHospital', primary_key=True, serialize=False)),
                ('codigo_hospital', models.CharField(db_column='codigoHospital', max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'Hospital',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HospitalServicio',
            fields=[
                ('idhospitalservicio', models.AutoField(db_column='idHospitalServicio', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(db_column='fechaInicio')),
                ('fecha_fin', models.DateField(blank=True, db_column='fechaFin', null=True)),
            ],
            options={
                'db_table': 'HospitalServicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idmedico', models.AutoField(db_column='idMedico', primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('apellidos_nombre', models.CharField(db_column='apellidosNombre', max_length=100)),
                ('fecha_nacimiento', models.DateField(db_column='fechaNacimiento')),
            ],
            options={
                'db_table': 'Medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicoHospitalServicio',
            fields=[
                ('idmedicohospitalservicio', models.AutoField(db_column='idMedicoHospitalServicio', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(db_column='fechaInicio')),
                ('fecha_fin', models.DateField(blank=True, db_column='fechaFin', null=True)),
            ],
            options={
                'db_table': 'MedicoHospitalServicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('codhist', models.AutoField(db_column='codHist', primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=9)),
                ('apellidos_nombre', models.CharField(db_column='apellidosNombre', max_length=100)),
                ('fecha_nacimiento', models.DateField(db_column='fechaNacimiento')),
                ('num_seguridad_social', models.CharField(db_column='numSeguridadSocial', max_length=15)),
                ('otros_datos', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idservicio', models.AutoField(db_column='idServicio', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(db_column='nombreCompleto', max_length=200)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('idvisita', models.AutoField(db_column='idVisita', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('diagnostico', models.CharField(max_length=255)),
                ('tratamiento', models.CharField(max_length=255)),
                ('es_ingreso', models.BooleanField(db_column='esIngreso', default=False)),
                ('fecha_alta', models.DateField(blank=True, db_column='fechaAlta', null=True)),
            ],
            options={
                'db_table': 'Visita',
                'managed': False,
            },
        ),
    ]
